###  Create a new domain
POST http://localhost:3000/contentmd
content-type: application/json

{
  "domain_name": "default",
  "creator_id": "{{$guid}}",
  "content_id": "acctname1/somedomainnamedt8",
  "title": "content title promo test8",
  "slug":  "content-title-promo-test8",
  "base_url": "/blog/override",
  "excerpt": "this topic is is a must read by t8",
  "images": "/blog/image01,alt01|/blog/image02,alt02",
  "content_type": "post",
  "file_type": "md",
  "word_cnt":  382 
}

### Get all contentmd in the default domain_id sorted in descending order by createdate
GET http://localhost:3000/contentmd

### Get all contentmd in the default domain_id sorted in ascending order by createdate
GET http://localhost:3000/contentmd?sortAscBy=createDate

### Get all contentmd in the specified domain_id by the default DESC sort order on createdate
GET http://localhost:3000/contentmd?domainName=emptydomain

### Get all contentmd in the specified domain_id in ASC order by createdate
GET http://localhost:3000/contentmd?sortAscBy=createDate&domainName=emptydomain

### Get contentmd by primary key id 
GET http://localhost:3000/contentmd/2

### Get content using slug as id
GET http://localhost:3000/contentmd/content-title-no4?useSlugAsId=true

### Update content metadata attributes
PATCH http://localhost:3000/contentmd/21
content-type: application/json

{
  "title": "content title promo test8 2ndpush",
  "slug":  "content-title-promo-test8-2ndpush",
  "base_url": "/blog/override"
}

###  Delete domain given id
DELETE http://localhost:3000/contentmd/8

###  Promote Content from current domain to another domain, by contentid
POST http://localhost:3000/contentmd/22/promote?toDomain=default
content-type: application/json

###  Promote Content from specified domain to another, by slug
POST http://localhost:3000/contentmd/slug/promote?fromDomain=default&toDomain=emptydomain&useSlugAsId=true
content-type: application/json

### ==================================================================
### API's Above This Line Have been implemented
### ==================================================================

### Get all contentmd in particular domain
GET http://localhost:3000/domain/1/contentmd


### Get all contentmd for my account


### Get domain by acctid
GET http://localhost:3000/domains?acctid=2


###  Route to signin  as existing user
# POST http://localhost:3000/auth/signin
# content-type: application/json

# {
#  "email": "testuser1@test.com",
#   "password": "12345"
# }

# ###  Route to signout 
# POST http://localhost:3000/auth/signout

# ### Get the currently signed in user
# GET http://localhost:3000/auth/whoami

# ###  Find user with particular ID
# GET http://localhost:3000/auth/2

# ###  Find all users with a given email 
# GET http://localhost:3000/auth?email=newemail@foo.com

# ###  Delete user with a given id
# DELETE http://localhost:3000/auth/1



