###  Route for signup, which creates a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "testuser1@test.com",
  "password": "12345"
}


###  Route to signin  as existing user
POST http://localhost:3000/auth/signin
content-type: application/json

{
 "email": "testuser1@test.com",
  "password": "12345"
}

###  Route to signout 
POST http://localhost:3000/auth/signout

### Get the currently signed in user
GET http://localhost:3000/auth/whoami

###  Find user with particular ID
GET http://localhost:3000/auth/2

###  Find all users with a given email 
GET http://localhost:3000/auth?email=newemail@foo.com

###  Delete user with a given id
DELETE http://localhost:3000/auth/1

###  update a user by id
PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "email": "newemail@foo.com"
}